version: '3' 

services:
  traefik:
    restart: always
    image: traefik:2.5
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true" # 도커를 서비스 공급자로 등록
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.forwardedHeaders.insecure=true" # 외부에서 들어오는 x-forwarded-* 헤더에 대한 허용, 해당 라인 삭제시 외부에서 전달되는 x-forwarded-* 헤더들은 모두 강제로 삭제처리하고 컨테이너에 전달됩니다. 운영/개발 환경에 맞게 설정. https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers
    container_name: traefik
    ports:
      - "80:80"     # The HTTP port
      - "443:443"     # The HTTPS port
      # - "8080:8080" # The Web UI (enabled by --api), 관리자 UI 접속을 위한 포트,  직접 포트를 노출해서 사용하려면 주석을 해제하고 아니라면 아래에 있는 라벨을 이용해서 도메인으로 접속합니다
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

    labels: # Web UI를 접속하기 위한 것도 트래픽을 통해 처리할 수 있습니다.
      - "traefik.http.routers.traefik.rule=Host(`localhost`)" # Web UI 접속을 위한 도메인. 사용자의 로컬 개발 환경에 맞게 변경해서 사용해야합니다
      - "traefik.http.services.traefik.loadbalancer.server.port=8080" # 관리 UI의 포트
