version: '3' 

services:
  traefik:
    restart: always
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    container_name: traefik
    #    network_mode: "host"
    ports:
      - "80:80"     # The HTTP port
      - "443:443"     # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

    labels:
      - "traefik.frontend.rule=Host:traefik.test"
      - "traefik.trontend.port=8080"

